FROM node:latest

ARG VITE_SERVER
ARG VITE_SOCKET
ARG NODE_ENV

ENV VITE_SERVER=$VITE_SERVER
ENV VITE_SOCKET=$VITE_SOCKET
ENV NODE_ENV=productio
WORKDIR ./app
COPY . .
RUN npm i
RUN npm run build
ENTRYPOINT ["node", "./server.js"]